[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://tova-ai-backend.onrender.com"